package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path"
)

const allUsersCanRead = 0o644

func main() {
	cwd, err := os.Getwd()
	if err != nil {
		panic(err)
	}

	pkg := os.Getenv("GOPACKAGE")
	log.Println("Running \"builttime\" on:", cwd)
	val, ok := os.LookupEnv("KN_PLUGIN_EVENT_SENDER_IMAGE")
	target := path.Join(cwd, "generated.go")
	code := fmt.Sprintf(`// Code generated by "knative.dev/kn-plugin-event/tools/builttime"; DO NOT EDIT.

package %s

var (
	imageFromEnvironment = "%s"
	imageFromEnvironmentSet = %t
)
`, pkg, val, ok)
	err = ioutil.WriteFile(target, []byte(code), allUsersCanRead)
	if err != nil {
		log.Fatal(err)
	}
}
