apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
  name: kn-plugin-event-sender-115
spec:
  componentName: kn-plugin-event-sender-115
  application: serverless-operator-135
   
  build-nudges-ref:
    
    - "serverless-bundle-135"
    
  
  source:
    git:
      url: https://github.com/openshift-knative/kn-plugin-event.git
      context: 
      dockerfileUrl: openshift/ci-operator/images/kn-event-sender/Dockerfile
      revision: release-1.15
