FROM docker.io/library/golang:1.17 AS builder

COPY . /code
WORKDIR /code

RUN go build \
  -o ./build/eventshub \
  knative.dev/reconciler-test/cmd/eventshub

FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

COPY --from=builder /code/build/eventshub /ko-app/eventshub

ENTRYPOINT ["/ko-app/eventshub"]
